project:
  type: website
  output-dir: docs

website:
  title: "Austin Kaduk"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Projects"
        href: projects.qmd
      - text: "Resume"
        href: about.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

